# Generated by Django 6.0.3 on 2026-04-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcompra',
            name='valor_aprox',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='prioridad',
            field=models.CharField(choices=[('urgente', 'Urgente'), ('alta', 'Alta'), ('normal', 'Normal'), ('postergable', 'Postergable')], default='normal', max_length=20),
        ),
    ]
