# Generated by Django 6.0.3 on 2026-04-08 16:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0002_itemcompra_valor_aprox_alter_gasto_monto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=0, max_digits=12)),
                ('tipo', models.CharField(choices=[('sueldo', 'Sueldo'), ('extra', 'Extra'), ('pyme', 'Pyme'), ('otro', 'Otro')], default='sueldo', max_length=20)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('es_fijo', models.BooleanField(default=False, help_text='Si es fijo se repite cada mes')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PagoRecurrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('monto', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('frecuencia', models.CharField(choices=[('mensual', 'Mensual'), ('cuotas', 'En cuotas')], default='mensual', max_length=20)),
                ('dia_pago', models.PositiveIntegerField(help_text='Día del mes en que se paga')),
                ('total_cuotas', models.PositiveIntegerField(blank=True, help_text='Solo si es en cuotas', null=True)),
                ('cuotas_pagadas', models.PositiveIntegerField(default=0)),
                ('prioridad', models.CharField(choices=[('urgente', 'Urgente'), ('alta', 'Alta'), ('normal', 'Normal'), ('postergable', 'Postergable')], default='normal', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gastos.categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_recurrentes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['dia_pago'],
            },
        ),
    ]
