# Generated by Django 6.0.3 on 2026-04-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0003_ingreso_pagorecurrente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagorecurrente',
            name='dia_semana',
            field=models.PositiveIntegerField(blank=True, help_text='0=Lunes, 6=Domingo', null=True),
        ),
        migrations.AlterField(
            model_name='pagorecurrente',
            name='frecuencia',
            field=models.CharField(choices=[('mensual', 'Mensual'), ('semanal', 'Semanal'), ('cuotas', 'En cuotas')], default='mensual', max_length=20),
        ),
    ]
