# Generated by Django 6.0.3 on 2026-04-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0004_pagorecurrente_dia_semana_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagorecurrente',
            name='dia_pago',
            field=models.PositiveIntegerField(blank=True, help_text='Día del mes 1-31', null=True),
        ),
    ]
