# Generated by Django 6.0.4 on 2026-04-16 23:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0005_alter_pagorecurrente_dia_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.CharField(help_text='Nombre de quien prestó o a quien prestaste', max_length=150)),
                ('concepto', models.CharField(help_text='Ej: Gastos médicos, Arriendo, Vacaciones', max_length=200)),
                ('monto_total', models.DecimalField(decimal_places=0, max_digits=12)),
                ('monto_pagado', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('tipo', models.CharField(choices=[('recibido', 'Me prestaron a mí'), ('otorgado', 'Yo presté dinero')], default='recibido', max_length=20)),
                ('estado', models.CharField(choices=[('vigente', 'Vigente'), ('saldado', 'Saldado'), ('vencido', 'Vencido')], default='vigente', max_length=20)),
                ('fecha_prestamo', models.DateField(default=django.utils.timezone.now)),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Fecha límite para pagar (opcional)', null=True)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-fecha_prestamo'],
            },
        ),
        migrations.CreateModel(
            name='PagoPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=0, max_digits=12)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('notas', models.CharField(blank=True, help_text='Ej: transferencia, efectivo', max_length=200)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='gastos.prestamo')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
