# Generated by Django 6.0.4 on 2026-04-17 15:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0006_prestamo_pagoprestamo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaAhorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Viaje a Buenos Aires', max_length=150)),
                ('icono', models.CharField(choices=[('🏖️', 'Viaje'), ('🏠', 'Casa'), ('🚗', 'Auto'), ('🎓', 'Educación'), ('🏥', 'Emergencia médica'), ('💼', 'Negocio'), ('🎁', 'Regalo'), ('📱', 'Tecnología'), ('💰', 'General'), ('🌟', 'Otro')], default='💰', max_length=5)),
                ('monto_objetivo', models.DecimalField(decimal_places=0, max_digits=12)),
                ('fecha_objetivo', models.DateField(blank=True, help_text='¿Para cuándo querés tenerlo?', null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_ahorro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meta de ahorro',
                'verbose_name_plural': 'Metas de ahorro',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='AporteMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=0, max_digits=12)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('notas', models.CharField(blank=True, max_length=200)),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aportes', to='gastos.metaahorro')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
