# Generated by Django 6.0.4 on 2026-04-18 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0007_metaahorro_aportemeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='es_fijo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='metaahorro',
            name='fecha_objetivo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metaahorro',
            name='icono',
            field=models.CharField(choices=[('🏖️', 'Viaje'), ('🏠', 'Casa'), ('🚗', 'Auto'), ('🎓', 'Educación'), ('🏥', 'Emergencia médica'), ('💼', 'Negocio'), ('🎁', 'Regalo'), ('📱', 'Tecnología'), ('💰', 'General'), ('🌟', 'Otro')], default='💰', max_length=10),
        ),
        migrations.AlterField(
            model_name='metaahorro',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='pagoprestamo',
            name='notas',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pagorecurrente',
            name='dia_pago',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagorecurrente',
            name='dia_semana',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagorecurrente',
            name='total_cuotas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='concepto',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='persona',
            field=models.CharField(max_length=150),
        ),
    ]
