# Generated by Django 6.0.4 on 2026-04-29 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0009_itemcompra_cantidad_comprada'),
        ('gastos', '0009_itemcompra_frecuencia'),
    ]

    operations = [
    ]
