# Generated by Django 6.0.4 on 2026-04-30 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0010_merge_20260429_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcompra',
            name='frecuencia',
        ),
    ]
