# Generated by Django 6.0.4 on 2026-05-16 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0011_remove_itemcompra_frecuencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('icono', models.CharField(default='🏪', max_length=10)),
            ],
            options={
                'verbose_name': 'Local de compra',
                'verbose_name_plural': 'Locales de compra',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='itemcompra',
            name='local_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='gastos.localcompra'),
        ),
    ]
